-- Intentionally a no-op.
--
-- This migration originally hand-patched `courses.requirement_groups`
-- for S2000 (add the Part A core groups the old extractor could not
-- derive) and F2010 (delete the Indonesia-only Part E so it never
-- auto-loaded). It sat unapplied in the ledger while both problems
-- were fixed at the source:
--
--   * S2000's SCI1000 force-load now comes from
--     packages/ingest/curriculum-overrides.json, re-applied by every
--     writer of requirement_groups (ingest, backfill:curriculum,
--     overrides:apply), so it survives re-ingest.
--   * F2010's Part E is now extracted WITH a campus scope tag
--     ("Indonesia") — visible in the requirements browser, never
--     auto-loaded. The original DELETE here would remove that group
--     against the current design.
--
-- Applying the original statements today would clobber rows baked by
-- the current extractor, so they are removed rather than left dormant.
SELECT 1;
