-- Originally: DROP TABLE session / account / verification, on the
-- premise that the MAC-auth cutover left them dead. Converted to a
-- no-op before it was ever applied, because the premise is wrong on
-- the shared database: `session` was still receiving live browser
-- sessions (multiple devices, latest 2026-07-02 09:05 UTC) when this
-- ledger entry came up for application. Either a deployment still runs
-- Better Auth, or the central MAC identity service shares this
-- database and owns these tables.
--
-- Do NOT resurrect the drops here — this file's hash is what the
-- migration ledger records. Once whatever is writing sessions is
-- identified and stopped (or confirmed to own its own schema), issue
-- the drops as a NEW migration.
--
-- (Historical intent, kept for context: the `user` table stays as a
-- local mirror so user_plan / user_grade FKs remain intact; its ids
-- equal the central macUserId.)
SELECT 1;
